// EBNF for Phobos language

Decl = FuncDecl | ImportDecl | TypeDecl | VarDecl .

FuncDecl = "func" [MethodType "."] Name Signature Body .

MethodType = identifier .

Name = identifier .

Signature = "(" [ ParameterList ] ")" [ "->" Returns ] .

ParameterList = Parameter { "," Parameter } .

Parameter = Name ":" Type .

Returns = Return | "(" Return { "," Return } ")" .

Return = [ Name ":" ] Type .

Body = Block .

Block = "{" { Statement } "}" .

Statement = ReturnStatement .

ReturnStatement = "return" [ ExpressionList ] .

ImportDecl = "import" QualifiedIdentifier .

QualifiedIdentifier = identifier { "." identifier } .

TypeDecl = "type" TypeName Type .

TypeName = identifier .

Type = ArrayType | EnumType | NameType | SliceType | StructType .

ArrayType = "[" ArrayLength "]" ElementType .

ElementType = Type .

EnumType = "enum" "{" { EnumItem } "}" .

EnumItem = identifier [ "=" Expr ] [ "," ] .

NameType = identifier { "." identifier } .

SliceType = "[" "]" ElementType .

StructType = "struct" "{" { Field } "}" .

Field = Name ":" Type [ "=" Expression ] .

VarDecl = "var" IdentifierList ( ":" Type [ "=" ExpressionList ] | "=" ExpressionList ) .

IdentifierList = identifier { "," identifier } .

ExpressionList = Expression { "," Expression } .

Expression = UnaryExpression | Expression BinaryOperator Expression .

UnaryExpression = Operand .

Operand = ( BasicLiteral | CompositeLiteral | identifier ) { Selector } .

BasicLiteral = string_literal .

CompositeLiteral = LiteralType LiteralValue .

LiteralType = ArrayType .

LiteralValue = "{" ElementList "}" .

ElementList = { Element "," } | Element { "," Element } .

Element = [ Key "=" ] ( Expression | LiteralValue ) .

Key = Index .

Index = "[" Expression "]" .

Selector = "." identifier .

BinaryOperator = .